/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import services.CommandeService;
import entities.Demande;
import entities.Produit;
import services.ClientService;
import entities.Fournisseur;
import entities.Sortie;
import entities.LigneDemande;
import entities.entree;
import entities.stock;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.DemandeService;
import services.EntreeService;
import services.FournisseurService;
import services.LigneCommandeService;
import services.LigneDemandeService;
import services.ProduitService;
import services.StockService;
import services.SortieService;
/**
 *
 * @author computer
 */
public class gestiondemande extends javax.swing.JInternalFrame {
    private FournisseurService cs;
    private DemandeService cms;
    private ProduitService ps;
    private EntreeService sts;
    private LigneDemandeService lcs;
    private DefaultTableModel model;
    private DefaultTableModel model2;
    private static int id;
    private static int commandesta;
    private static  int produitsta;
    private StockService ss;
    private static  int quantitesta;
    
 
    public gestiondemande() {
        initComponents();
          this.setTitle("Gestion des demandes");
        cs = new FournisseurService();
        cms = new  DemandeService();
        lcs = new LigneDemandeService();
        ps = new ProduitService();
        ss = new StockService();
        sts = new EntreeService();
        
        loadclient();
        loaddemande2();
        loadproduit();
       
        model = (DefaultTableModel) listdemande.getModel();
        model2 = (DefaultTableModel) listlignecommande.getModel();
        loadlignedemande();
        loaddemande();
        
    }

    
  private void loaddemande() {
        model.setRowCount(0);
        for (Demande c : cms.findAll()) {
            model.addRow(new Object[]{
                c.getId(),
                c.getDate(),
               c.getFournisseur().getId()
                });
        }
    }

    private void loadclient() {
        for (Fournisseur s : cs.findAll()) {
            listfournisseur.addItem(s.getId());
        }
    }
    private void loadlignedemande() {
        model2.setRowCount(0);
        for (LigneDemande l : lcs.findAll()) {
            model2.addRow(new Object[]{
                l.getDemande().getId(),
                l.getProduit().getId(),
                l.getPrix(),
                l.getQuantite()
                });
        }
    }

    private void loadproduit() {
        for (Produit s : ps.findAll()) {
            listproduit.addItem(s.getId());
        }
    }
    private void loaddemande2() {
        for (Demande s : cms.findAll()) {
            listdemande2.addItem(s.getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDate5 = new com.toedter.calendar.JDateChooser();
        Ajouter = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        listfournisseur = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listdemande = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        listdemande2 = new javax.swing.JComboBox();
        listproduit = new javax.swing.JComboBox();
        txtquantite = new javax.swing.JTextField();
        txtprix = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listlignecommande = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("information demande"));

        jLabel1.setText("date");

        jLabel2.setText("fournisseur");

        Ajouter.setText("Ajouter");
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterActionPerformed(evt);
            }
        });

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        listfournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listfournisseurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDate5, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(listfournisseur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(181, 181, 181)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtDate5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ajouter))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(listfournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(modifier))
                .addGap(18, 18, 18)
                .addComponent(supprimer)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("list des demandes"));

        listdemande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "date", "client"
            }
        ));
        listdemande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listdemandeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listdemande);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("information ligne demande"));

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("quantite");

        jLabel4.setText("prix");

        jLabel5.setText("Demande");

        jLabel6.setText("produit");

        txtquantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtprix, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(listdemande2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listproduit, 0, 112, Short.MAX_VALUE)
                    .addComponent(txtquantite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(listdemande2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(listproduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtquantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtprix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("list des lignes de demande"));

        listlignecommande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "commande", "produit", "prix", "quantite"
            }
        ));
        listlignecommande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listlignecommandeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listlignecommande);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
         
        
        Date date = txtDate5.getDate();
        int c = (int) listfournisseur.getSelectedItem();
        if (cms.update(new Demande(id, date ,cs.findById(c)))) {
            JOptionPane.showMessageDialog(this, "Bien modifié");
            loaddemande();           
            
            
            
        
        }
    }//GEN-LAST:event_modifierActionPerformed

    private void listfournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listfournisseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listfournisseurActionPerformed

    private void AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterActionPerformed

       Date date = txtDate5.getDate();
       int answer = 0;
        int c =  (int) listfournisseur.getSelectedItem();
        
        if (cms.create(new Demande(date,cs.findById(c)))) {
            JOptionPane.showMessageDialog(this, "Bien ajouté");
            loaddemande();
            loaddemande2();
          answer=1;
        }
        if(answer==1){
            sts.create(new entree(0, cms.findByFournisseur(cs.findById(c))));
        }
    }//GEN-LAST:event_AjouterActionPerformed

    private void listdemandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listdemandeMouseClicked
         id = Integer.parseInt(model.getValueAt(listdemande.getSelectedRow(), 0).toString());
        txtDate5.setDate((Date) model.getValueAt(listdemande.getSelectedRow(), 1));
        listfournisseur.setSelectedItem((int)model.getValueAt(listdemande.getSelectedRow(), 2));
    }//GEN-LAST:event_listdemandeMouseClicked

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
          int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous bien supprimer cette commande ?");
        if (reponse == 0 && id != 0) {  

            cms.delete(cms.findById(id));
            JOptionPane.showMessageDialog(this, "Bien supprimé");
            loaddemande();
            loaddemande2();
            
           
        }
    }//GEN-LAST:event_supprimerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        int quantite = Integer.parseInt(txtquantite.getText());
        Double prix = Double.parseDouble(txtprix.getText());
        int p =  (int) listproduit.getSelectedItem();
        int cm =  (int) listdemande2.getSelectedItem();
        int q= ss.findById(p).getQuantite();
        int newq =q+quantite;
        
         
             if(lcs.create(new LigneDemande(quantite, prix, cms.findById(cm), ps.findById(p)))) {
            JOptionPane.showMessageDialog(this, "Bien ajouté");
            loadlignedemande();
            ss.update(new stock(ps.findById(p), newq));
            
            
            
          
        }
        
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listlignecommandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listlignecommandeMouseClicked
       commandesta= Integer.parseInt(model2.getValueAt(listlignecommande.getSelectedRow(), 0).toString());
       produitsta= Integer.parseInt(model2.getValueAt(listlignecommande.getSelectedRow(), 1).toString());
    
       quantitesta= Integer.parseInt(model2.getValueAt(listlignecommande.getSelectedRow(), 3).toString());
       
       listdemande2.setSelectedItem((int)model2.getValueAt(listlignecommande.getSelectedRow(), 0));
       listproduit.setSelectedItem((int)model2.getValueAt(listlignecommande.getSelectedRow(), 1));
         txtquantite.setText(model2.getValueAt(listlignecommande.getSelectedRow(), 3).toString());
         txtprix.setText(model2.getValueAt(listlignecommande.getSelectedRow(), 2).toString());
       
    }//GEN-LAST:event_listlignecommandeMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous bien supprimer cette demande ?");
        if (reponse == 0 ) {
            int p =  (int) listproduit.getSelectedItem();
            int q= ss.findById(p).getQuantite();
            int newq =q-quantitesta;
            ss.update(new stock(ps.findById(p), newq));
           lcs.delete(new LigneDemande(quantitesta, 0, cms.findById(commandesta), ps.findById(produitsta)));
           JOptionPane.showMessageDialog(this, "Bien supprimé");
            loadlignedemande();
           
        }
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtquantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantiteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listdemande;
    private javax.swing.JComboBox listdemande2;
    private javax.swing.JComboBox listfournisseur;
    private javax.swing.JTable listlignecommande;
    private javax.swing.JComboBox listproduit;
    private javax.swing.JButton modifier;
    private javax.swing.JButton supprimer;
    private com.toedter.calendar.JDateChooser txtDate5;
    private javax.swing.JTextField txtprix;
    private javax.swing.JTextField txtquantite;
    // End of variables declaration//GEN-END:variables
}
