/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import entities.entree;
import entities.LigneDemande;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.FournisseurService;
import services.DemandeService;
import services.EntreeService;
import services.LigneDemandeService;

/**
 *
 * @author computer
 */
public class gestionEntree extends javax.swing.JInternalFrame {
private FournisseurService cs;
private EntreeService ss;
private DemandeService cms;
private LigneDemandeService lcs;
private DefaultTableModel model;
private static int id ;

    /**
     * Creates new form gestionSortie
     */
    public gestionEntree() {
        
          initComponents();
          ss= new EntreeService();
          lcs = new LigneDemandeService();
          cs = new FournisseurService();
        model=(DefaultTableModel) listSortie.getModel();
        load();
    }
   public void load (){
       int q;
       double p;
       int nbr;
       
    model.setRowCount(0);
    for(entree c : ss.findAll() ){
        q=0;p=0;nbr=0; 
        for(LigneDemande s : lcs.findAll()){
        if(s.getDemande().getId()==c.getDemande().getId()){
            double pq = 0;
            pq=s.getPrix()*s.getQuantite();
            nbr=nbr+1;
            q=q+s.getQuantite();
            p=p+pq;
            
        }
        
        }
        model.addRow(new Object[]{
            c.getDemande().getId(),
            c.getDemande().getFournisseur().getNom(),
            nbr,
            q,
            p,
            c.getDemande().getDate(),
                c.getId()
            
                
            
            
                
        });
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSortie = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("liste des sorties"));

        listSortie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "demande id", "fournisseur", "Nbr de produit", "quantite total", "prix total", "Date", "Entree id "
            }
        ));
        listSortie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listSortieMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listSortie);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setText("Supprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            if(id!=0){
            int reponse =JOptionPane.showConfirmDialog(this, "voulez  vous vraiment supprimer cette entree");
            if (reponse==0){
                ss.delete(ss.findById(id));
                load();
                JOptionPane.showMessageDialog(this, "Bien supprimé");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listSortieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listSortieMouseClicked
         id = Integer.parseInt(model.getValueAt(listSortie.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_listSortieMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listSortie;
    // End of variables declaration//GEN-END:variables
}
