/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import com.formdev.flatlaf.FlatDarkLaf;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author computer
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        this.setTitle("gestion des sortie");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        produitMenuItem = new javax.swing.JMenuItem();
        clientMenuItem = new javax.swing.JMenuItem();
        commandeMenuItem = new javax.swing.JMenuItem();
        stockMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        produitMenuItem.setMnemonic('o');
        produitMenuItem.setText("Produit");
        produitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(produitMenuItem);

        clientMenuItem.setMnemonic('s');
        clientMenuItem.setText("Fournisseur");
        clientMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(clientMenuItem);

        commandeMenuItem.setMnemonic('a');
        commandeMenuItem.setText("Demande");
        commandeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commandeMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(commandeMenuItem);

        stockMenuItem.setMnemonic('x');
        stockMenuItem.setText("Stock");
        stockMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(stockMenuItem);

        jMenuItem1.setText("Entree");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stockMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockMenuItemActionPerformed
        gestionstock gs = new gestionstock();
        desktopPane.add(gs);
        gs.setVisible(true);
    }//GEN-LAST:event_stockMenuItemActionPerformed

    private void produitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produitMenuItemActionPerformed
        // TODO add your handling code here:
        gestionproduit gp = new gestionproduit();
        desktopPane.add(gp);
        gp.setVisible(true);
    }//GEN-LAST:event_produitMenuItemActionPerformed

    private void clientMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientMenuItemActionPerformed
        gestionfournisseur gc = new gestionfournisseur();
        desktopPane.add(gc);
        gc.setVisible(true);
    }//GEN-LAST:event_clientMenuItemActionPerformed

    private void commandeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commandeMenuItemActionPerformed
        // TODO add your handling code here:
        gestiondemande gmc = new gestiondemande();
        desktopPane.add(gmc);
        gmc.setVisible(true);
    }//GEN-LAST:event_commandeMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
          gestionEntree gs = new gestionEntree();
        desktopPane.add(gs);
        gs.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem clientMenuItem;
    private javax.swing.JMenuItem commandeMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem produitMenuItem;
    private javax.swing.JMenuItem stockMenuItem;
    // End of variables declaration//GEN-END:variables

}
